-- Sekian Info v2 — Initial Database Schema
-- Migration: 001_initial_schema.sql

-- ============================================================
-- Table: daily_digest
-- Stores daily curated Indonesian news summaries
-- ============================================================
CREATE TABLE daily_digest (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date        DATE NOT NULL,
  title       TEXT NOT NULL,
  summary     TEXT NOT NULL,
  slug        TEXT NOT NULL,
  source      TEXT NOT NULL,
  source_url  TEXT NOT NULL,
  category    TEXT,
  raw_json    JSONB,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(date, slug)
);

CREATE INDEX idx_daily_digest_date ON daily_digest(date DESC);
CREATE INDEX idx_daily_digest_slug ON daily_digest(slug);

-- ============================================================
-- Table: market_data
-- Stores daily Indonesian market data (IHSG, USD/IDR, gold)
-- ============================================================
CREATE TABLE market_data (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date        DATE NOT NULL UNIQUE,
  ihsg        NUMERIC,
  ihsg_change NUMERIC,
  usd_idr     NUMERIC,
  gold_price  NUMERIC,
  top_gainer  JSONB,   -- Array of { code, name, change_pct }
  top_loser   JSONB,   -- Array of { code, name, change_pct }
  ai_insight  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_market_data_date ON market_data(date DESC);

-- ============================================================
-- Table: ai_news_digest
-- Stores daily curated AI news digest with developer impact
-- ============================================================
CREATE TABLE ai_news_digest (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date        DATE NOT NULL UNIQUE,
  items       JSONB NOT NULL,  -- Array of { title, summary, impact, source, link }
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_ai_news_date ON ai_news_digest(date DESC);

-- ============================================================
-- Table: inspirasi_harian
-- Stores Islamic inspirational content (Quran, Hadits, Quotes)
-- ============================================================
CREATE TABLE inspirasi_harian (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type          TEXT NOT NULL CHECK (type IN ('quran', 'hadits', 'quote')),
  content       TEXT NOT NULL,
  reference     TEXT,          -- e.g. "QS. Al-Baqarah: 286"
  selected_date DATE           -- Set when this content is selected for a given day
);

CREATE INDEX idx_inspirasi_selected_date ON inspirasi_harian(selected_date DESC);

-- ============================================================
-- Table: article_cache
-- Stores on-demand article summaries generated by LLM
-- ============================================================
CREATE TABLE article_cache (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        TEXT NOT NULL UNIQUE,
  title       TEXT NOT NULL,
  summary     TEXT,
  key_points  JSONB,           -- Array of string (max 5)
  source_url  TEXT NOT NULL,
  source_name TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_article_cache_slug ON article_cache(slug);

-- ============================================================
-- Table: trending_data
-- Stores cached Google Trends data for Indonesia
-- ============================================================
CREATE TABLE trending_data (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date        DATE NOT NULL UNIQUE,
  topics      JSONB NOT NULL,  -- Array of { keyword, search_volume }
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_trending_date ON trending_data(date DESC);
